### ISSUE TITLE
感谢大佬，Z7M-SL7已成功吃上黑苹果

### ISSUE THREAD

**Issue by wjllp** [Yunkong690/Z7M_SL5D1_Hackintosh#1]
之前自己做的efi老是有各种问题，今天无意中发现大佬的efi，开机一试居然近乎完美。
不过我这边使用这个efi目前还是有几个小问题：

> 蓝牙：关闭蓝牙的按钮是灰色，无法关闭

> 触控板：手势、轻触都ok，但是用触控板下面的左右键点击的时候无反应

> 节能：节能只有3项，不是5项

其他的基本ok，近乎完美

**Comment by wjllp** [comment]
目前发现传感器驱动有问题，FaceTime、iMessage不可用，把SMC那几个驱动升级到最新版本就可以了

**Comment by Yunkong690** [comment]
我的就风扇转速读不到，DW1820A网卡一切正常，Big Sur下的HDMI无解，15.6下可以用，HDMI这个问题头大

**Comment by Yunkong690** [comment]
> 目前发现传感器驱动有问题，FaceTime、iMessage不可用，把SMC那几个驱动升级到最新版本就可以了
我的就风扇转速读不到，DW1820A网卡一切正常，Big Sur下的HDMI无解，15.6下可以用，HDMI这个问题头大

**Comment by wjllp** [comment]
你的WhateverGreen.kext是最新版本的吗，升级到最新版本或许能支持big sur

**Comment by wjllp** [comment]
FaceTime、iMessage搞定了，板载Intel无限网卡也通过itlwm驱动了，不过屏幕亮度还是不能用快捷键调，你的可以用快捷键调亮度吗

**Comment by wjllp** [comment]
你的机型设置的不太合适，MacBook Pro 15,1是2019款8代cpu的笔记本，6代的应该设置为MacBook Pro 13,3比较合适

**Comment by Yunkong690** [comment]
> FaceTime、iMessage搞定了，板载Intel无限网卡也通过itlwm驱动了，不过屏幕亮度还是不能用快捷键调，你的可以用快捷键调亮度吗

亮度是fn+ins 和fn+pg up

**Comment by Yunkong690** [comment]
> 你的机型设置的不太合适，MacBook Pro 15,1是2019款8代cpu的笔记本，6代的应该设置为MacBook Pro 13,3比较合适

就算设置为13.3 big surx下HDMI还是不能输出，我在15.6下，机型为15.4都可以

**Comment by wjllp** [comment]
你开机前插上HDMI，开机后笔记本屏幕和外接屏幕都能正常显示吗

**Comment by yf-hk** [comment]
可以分享下怎样装的 Big Sur 吗？

**Comment by Yunkong690** [comment]
> 可以分享下怎样装的 Big Sur 吗？

本项目已停止更新，最新版请移步 https://github.com/Yunkong690/HASEE_Z7M_SL5-7-D1_OC_EFI
