### ISSUE TITLE
我也是hd530,独显是960m,我的核显无法使用hdmi输出

### ISSUE THREAD

**Issue by beilvla** [Yunkong690/Z7M_SL5D1_Hackintosh#2]
我也是hd530,独显是960m,我的核显无法使用hdmi输出，大佬你的0.6.7那个包支持hdmi输出么？

**Comment by Yunkong690** [comment]
我的机型可以，你的机型我不知道

**Comment by beilvla** [comment]
我不太了解补丁这个东西  但是我可以给你看看我的配置图   大佬帮忙看一下

**Comment by beilvla** [comment]
![2271618801068_ pic](https://user-images.githubusercontent.com/34034894/115175805-4d108e00-a0fe-11eb-9f98-a162bd7e4e93.jpg)


![2261618801067_ pic](https://user-images.githubusercontent.com/34034894/115175820-53066f00-a0fe-11eb-9567-b174df3c5da9.jpg)

**Comment by Yunkong690** [comment]
我已经很久不管黑苹果了，你自己照着我的efi整吧

**Comment by Yunkong690** [comment]
你首先确定一下hdmi走的独显还是核显

**Comment by beilvla** [comment]
走的核显

**Comment by beilvla** [comment]
好的  谢谢大佬
